### PR TITLE
fix: Apply the style value according to RFC6570.

### LINKED ISSUE #4: Simple path style returns undefined for a plain string value
A path parameter of style `simple` (default) is returning `undefined` for a plain string. Seems it [only allows for an array](https://github.com/Himenon/openapi-parameter-formatter/blob/41ea27dd955c884735ef1c6844e02b9324cbfff1/src/Core.ts#L12).

I can see why this one is a bit confusing in [the spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#style-values), as it states `simple` is type `array`.

However you can see in both the [rfc6570 spec](https://tools.ietf.org/html/rfc6570#section-3.2.2) it references and the [examples](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#style-examples), that it supports individual strings and objects.

Thanks for the library.

### PR DESCRIPTION
**Pull request by Himenon**
* fix #4

### CODE REVIEW

File: src/__tests__/PathParameter-test.ts [hunk 1]
```diff
@@ -1,5 +1,101 @@
...
+    const result3 = PathParameter.generate("color", {
+      value: {
+        R: 100,
+        G: undefined,
+        B: 150,
+      },
+      style: "simple",
+      explode: true,
+    });
+    expect(result3).toBe("R=100,G=,B=150");
```
Comment (Himenon) [inline src/__tests__/PathParameter-test.ts:85]: https://tools.ietf.org/html/rfc6570#section-3.2.2
